### PR TITLE
fix angle when mode = XFCE_PANEL_PLUGIN_MODE_VERTICAL

### PR DESCRIPTION
**Pull request by monperrus**
add support for new DESKBAR mode in XFCE 4.10, see https://www.xfce.org/about/tour410

### CODE REVIEW

**Comment by andreldm** [comment]
datetime-plugin already looks fine on Deskbar mode, there is no need to treat it differently than horizontal mode.

**Comment by monperrus** [comment]
It looks fine if the panel mode is "Horizontal" or "Deskbar".

It does not look fine if the panel mode is "Vertical" (the hour is displayed vertical instead of horizontal).

**Comment by andreldm** [comment]
All plugins I have here are rotated 90° when in vertical mode, I guess that's what deskbar is supposed to fix. Probably the vertical mode was kept for whatever use cases may need rotated plugins.
If my memory serves me well, at some point the current panel maintainer (@ochosi) already considered to drop vertical mode.

**Comment by andreldm** [comment]
Hi Martin, if you're still interested in this, can you please open a merge request at https://gitlab.xfce.org/panel-plugins/xfce4-datetime-plugin? Thanks!

cc @ochosi

**Pull request closed without merging**
